### ISSUE TITLE
Documentation for async/await support (in 0.2)

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/futures-rs#927]
Some issues I have noticed with the current documentation when building with `--features nightly`:

 - [x] (#928) `futures::__rt` is visible, this should be hidden
 - [ ] `async` etc. macros are only in the prelude, for documentation (and people that avoid preludes) I believe these should also be exported from the root (or maybe some other submodule? module name bikeshed welcome)
 - [ ] No mention of what nightly features are required to use `async`, should include basics from `futures-await.md`
 - [x] (#964) Consistency of attributes (#918)
 - [ ] The macros appear as re-exports instead of items (rust-lang/rust#49554)
 - [ ] `async*` macros links from `futures::prelude` don't work (rust-lang/rust#49553)
 - [ ] ([WIP branch](https://github.com/Nemo157/futures-rs/compare/consistent-async-args...async-docs)) `async*` macros have no documentation
 - [x] (#930) `await!` documentation is internal implementation details, should be user facing
 - [x] (#930) `await_item!` documentation is lacking
 - [x] (#930) `stream_yield!` is missing documentation

**Comment by Nemo157** [comment]
Outdated
